name: CI/CD pipline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push-to-dh:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker assignee image
        run: |
          docker build ./assignee -f ./assignee/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/assignee:latest ./assignee


      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push assignee service image
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/assignee-service:latest


